#!/bin/bash

INPUT=input.txt
(( TEST )) && INPUT=test.txt
(( TEST > 1 )) && INPUT=test$TEST.txt
(( TEST )) && DEBUG=1

function debug
{
	(( DEBUG )) || return 0
	if (( $# )); then
		printf "$@" >&2
	else
		echo >&2
	fi
}

function error
{
	printf "$@" >&2
	exit 1
}

function ReadStuff
{
	local LINE RE='^Stuff$'
	while read LINE ; do
		debug "Read [%s]\n" "$LINE"
		if [[ "$LINE" =~ $RE ]]; then
			(( NUMTHINGS++ ))
		else
			error "Could not parse '%s'\n" "$LINE"
		fi
	done
}

function DoThing
{
	local INPUT="$1"
	local -i NUMTHINGS=0
	ReadStuff < $INPUT
	printf "Result: %s\n" $NUMTHINGS
}

DoThing $INPUT ; exit $?
