#!/bin/bash

INPUT=input.txt
(( TEST )) && INPUT=test.txt

printf -v SCOREPOS "%c" ' ' {a..z} {A..Z}

function SumBadgePriorities
{
	local INPUT="$1"
	local LINE1 LINE2 LINE3
	local -i LEN I SCORE SUM=0
	local -A LET
	while read LINE1 ; do
		read LINE2
		read LINE3
		LET=()
		(( LEN = ${#LINE1} ))
		for (( I = 0 ; I < LEN ; I++ )); do
			(( LET[${LINE1:I:1}] = 1 ))
		done
		(( LEN = ${#LINE2} ))
		for (( I = 0 ; I < LEN ; I++ )); do
			(( LET[${LINE2:I:1}] |= 2 ))
		done
		(( LEN = ${#LINE3} ))
		for (( I = 0 ; I < LEN ; I++ )); do
			if (( LET[${LINE3:I:1}] == 3 )); then
				SCRE="^([^${LINE3:I:1}]*)"
				if [[ "$SCOREPOS" =~ $SCRE ]]; then
					(( SCORE = ${#BASH_REMATCH[1]} ))
					(( SUM += SCORE ))
				else
					echo "Not a letter"
					exit 1
				fi
				break
			fi
		done
	done < $INPUT
	echo "Sum of badge priorities = $SUM"
}

SumBadgePriorities $INPUT
