#!/bin/bash

function crabalign
{
	CRAB=()
	(( MINPOS = 10**9 ))
	(( MAXPOS = 0 ))
	(( SUM = 0 ))
	(( COUNT = 0 ))
	while (( $# )); do
		(( CRAB[$1]++ ))
		(( MINPOS = (MINPOS < $1) ? MINPOS : $1 ))
		(( MAXPOS = (MAXPOS > $1) ? MAXPOS : $1 ))
		(( SUM += $1 ))
		(( COUNT++ ))
		shift
	done
	echo "Range $MINPOS to $MAXPOS"
	echo "Total $SUM  Count $COUNT  Mean $((SUM / COUNT ))"
	POS=( ${!CRAB[@]} )
	NUMPOS=${#POS[@]}
	(( TOT = 0 ))
	for (( N = 0 ; N < NUMPOS ; N++ )); do
		(( POSN = POS[N] ))
		(( TOT += CRAB[POSN] ))
		if (( TOT > COUNT / 2 )); then
			break
		fi
	done
	(( MEDIAN = POSN ))
	(( MEDIANN = N ))
	echo "Median = $MEDIAN"
	(( FUEL = 0 ))
	(( N = 0 ))
	for (( N = 0 ; N < MEDIANN ; N++ )); do
		(( POSN = POS[N] ))
		(( FUEL += (MEDIAN - POSN) * CRAB[POSN] ))
	done
	for (( N = MEDIANN + 1 ; N < NUMPOS ; N++ )); do
		(( POSN = POS[N] ))
		(( FUEL += (POSN - MEDIAN) * CRAB[POSN] ))
	done
	echo "Fuel used $FUEL"
}

INPUT=$(< input.txt)

crabalign ${INPUT//,/ }
