#!/bin/bash

INPUT=input.txt
(( TEST )) && INPUT=test.txt
(( TEST > 1 )) && INPUT=test$TEST.txt
(( TEST )) && DEBUG=1

function debug
{
	(( DEBUG )) || return 0
	if (( $# )); then
		printf "$@" >&2
	else
		echo >&2
	fi
}

function error
{
	printf "$@" >&2
	exit 1
}

function ReadCards
{
	local LINE RE='^Card *[1-9][0-9]*: ([0-9 ]+) \| ([0-9 ]+)$'
	local -i WINNUM=() N POINTS
	while read LINE ; do
		debug "Read [%s]\n" "$LINE"
		if [[ "$LINE" =~ $RE ]]; then
			WINNUM=()
			for N in ${BASH_REMATCH[1]} ; do
				(( WINNUM[N] = 1 ))
			done
			POINTS=0
			for N in ${BASH_REMATCH[2]} ; do
				if (( WINNUM[N] )); then
					(( POINTS *= 2 )) || (( POINTS = 1 ))
				fi
			done
			debug "Points = %d\n" "$POINTS"
			(( TOTALPOINTS += POINTS ))
		else
			error "Could not parse '%s'\n" "$LINE"
		fi
	done
}

function SumPoints
{
	local INPUT="$1"
	local -i TOTALPOINTS=0
	ReadCards < $INPUT
	printf "Result: %s\n" $TOTALPOINTS
}

SumPoints $INPUT ; exit $?
