#!/bin/bash

function navigate
{
	POSITION=0
	DEPTH=0
	AIM=0
	while (( $# )); do
		case $1 in
			forward ) (( POSITION += $2 )) ; (( DEPTH += AIM * $2 )) ;;
			down )    (( AIM += $2 )) ;;
			up )      (( AIM -= $2 )) ;;
		esac
		shift 2
	done
	echo "Position $POSITION  Depth $DEPTH"
	echo "Multiplied = $(( POSITION * DEPTH ))"
}

INPUT=( $(< input.txt) )

navigate "${INPUT[@]}"

