#!/bin/bash

INPUT=input.txt
(( TEST )) && INPUT=test.txt

declare -A SCORE=(
	"A X" 4  "A Y" 8  "A Z" 3
	"B X" 1  "B Y" 5  "B Z" 9
	"C X" 7  "C Y" 2  "C Z" 6
)

function CalcTotalScore
{
	local INPUT="$1"
	local LINE
	local -i TOTALSCORE=0
	while read LINE ; do
		(( TOTALSCORE += SCORE["$LINE"] ))
	done < $INPUT
	echo "Total score = $TOTALSCORE"
}

CalcTotalScore $INPUT
