#!/bin/bash

INPUT=input.txt
(( TEST )) && INPUT=test.txt

# 0-1 2_3
# 0-2=1_3
# 0-2=3-1 *
# 2_0=1_3 *
# 2_0=3-1
# 2_3 0-1 

function CountContainedRanges
{
	local INPUT="$1"
	local LINE SECTIONS=()
	local IFS=',-'
	local -i COUNT=0
	while read LINE ; do
		SECTIONS=( $LINE )
		if (( SECTIONS[0] <= SECTIONS[2] && SECTIONS[1] >= SECTIONS[3] )); then
				(( COUNT++ ))
		elif (( SECTIONS[2] <= SECTIONS[0] && SECTIONS[3] >= SECTIONS[1] )); then
				(( COUNT++ ))
		fi
	done < $INPUT
	echo "Number of contained ranges = $COUNT"
}

CountContainedRanges $INPUT
