#!/bin/bash

INPUT=input.txt
(( TEST )) && INPUT=test.txt

function savetopsums
{
	if (( SUM > MAXSUM[0] )); then
		if (( SUM > MAXSUM[1] )); then
			(( MAXSUM[0] = MAXSUM[1] ))
			if (( SUM > MAXSUM[2] )); then
				(( MAXSUM[1] = MAXSUM[2] ))
				(( MAXSUM[2] = SUM ))
			else
				(( MAXSUM[1] = SUM ))
			fi
		else
			(( MAXSUM[0] = SUM ))
		fi
	fi
}

function Find3MaxFood
{
	local INPUT="$1"
	local -i SUM=0
	local MAXSUM=( 0 0 0 )

	while read LINE ; do
		if [[ -z "$LINE" ]]; then
			savetopsums
			(( SUM = 0 ))
		else
			(( SUM += LINE ))
		fi
		#echo "$LINE -> $SUM -> ${MAXSUM[@]}"
	done < $INPUT
	savetopsums
	echo "Maximum food carried = ${MAXSUM[0]} + ${MAXSUM[1]} + ${MAXSUM[2]} = $((MAXSUM[0]+MAXSUM[1]+MAXSUM[2]))"
}

Find3MaxFood $INPUT
